sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rksingh007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rksingh007/docker-react npm run test
